#!/usr/bin/env bash
# The script displays Best School and on the 4 iteration prints bad luck and at 8th iteration displays good luck

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
