#!/usr/bin/env bash
# Displays numbers from 1 to 20 and at the 4th iteration it displays bad luck from china and 9th iteration bad luck from japan and 17th displays bad luck from Italy

i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan "
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
